/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerate with `node scripts/refresh-catalog.mjs`, which probes every declared
 * /models endpoints and the CodeCommand capability reference, then diffs the result
 * against this file (+added -removed ~changed).
 *
 * Schema: `types.ts`. Endpoints and API key variables: `sources.ts` (the generator
 * imports both, so neither the types nor the URLs are duplicated here).
 *
 * Fields the wire cannot supply (`maxTokens`, `thinkingLevelMap`) are preserved from
 * the previous catalog; new ids fall back to family defaults and are reported.
 *
 * `cost` is always present: pi requires it (`calculateCost` dereferences
 * `model.cost`). These are subscription lanes with no per-token price, so cost is zero.
 */
import type { CatalogModel, VendorId } from "./types.ts";

export const CATALOG: Record<VendorId, CatalogModel[]> = {
	"commandcode": [
		{ id: "claude-sonnet-5", name: "Claude Sonnet 5", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"xhigh":"xhigh","max":"max"} },
		{ id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"max":"max"} },
		{ id: "claude-fable-5-1", name: "Claude Fable 5.1", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"off":null,"xhigh":"xhigh","max":"max"} },
		{ id: "claude-fable-5", name: "Claude Fable 5", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"off":null,"xhigh":"xhigh","max":"max"} },
		{ id: "claude-opus-5", name: "Claude Opus 5", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "claude-opus-4-8", name: "Claude Opus 4.8", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"xhigh":"xhigh","max":"max"} },
		{ id: "claude-opus-4-7", name: "Claude Opus 4.7", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"xhigh":"xhigh","max":"max"} },
		{ id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5", api: "anthropic-messages", reasoning: true, input: ["text","image"], contextWindow: 200000, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "gpt-5.6-sol", name: "GPT-5.6 Sol", reasoning: true, input: ["text","image"], contextWindow: 1050000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.6-terra", name: "GPT-5.6 Terra", reasoning: true, input: ["text","image"], contextWindow: 1050000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.6-luna", name: "GPT-5.6 Luna", reasoning: true, input: ["text","image"], contextWindow: 1050000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.5", name: "GPT-5.5", reasoning: true, input: ["text","image"], contextWindow: 400000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.4", name: "GPT-5.4", reasoning: true, input: ["text","image"], contextWindow: 400000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.3-codex", name: "GPT-5.3 Codex", reasoning: true, input: ["text","image"], contextWindow: 400000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "gpt-5.4-mini", name: "GPT-5.4 Mini", reasoning: true, input: ["text","image"], contextWindow: 400000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro (latest)", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash (latest)", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision (exp)", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "deepseek/deepseek-v4-flash-fast", name: "DeepSeek V4 Flash Fast", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "moonshotai/Kimi-K3", name: "Kimi K3", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "moonshotai/Kimi-K2.7-Code-Highspeed", name: "Kimi K2.7 Code HighSpeed", reasoning: true, input: ["text","image"], contextWindow: 262000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "z-ai/glm-5.3-flash", name: "GLM-5.3 Flash", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "zai-org/GLM-5.3", name: "GLM-5.3", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "zai-org/GLM-5.2", name: "GLM-5.2", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "zai-org/GLM-5.2-Fast", name: "GLM-5.2 Fast", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "zai-org/GLM-5.1", name: "GLM-5.1", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "zai-org/GLM-5", name: "GLM-5", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 128000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "xiaomi/mimo-v2.5", name: "MiMo V2.5", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "Qwen/Qwen3.8-Omni-Flash", name: "Qwen 3.8 Omni Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.8-Max-0902", name: "Qwen 3.8 Max 0902", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.8-Max", name: "Qwen 3.8 Max", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.8-27B", name: "Qwen 3.8 27B", reasoning: true, input: ["text","image"], contextWindow: 262144, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.8-Flash", name: "Qwen 3.8 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.7-Max", name: "Qwen 3.7 Max", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.7-Plus", name: "Qwen 3.7 Plus", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.7-Flash", name: "Qwen 3.7 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max Preview", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus", reasoning: true, input: ["text","image"], contextWindow: 200000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meituan/LongCat-2.0:free", name: "LongCat 2.0", reasoning: true, input: ["text"], contextWindow: 1048576, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "stepfun/Step-3.7-Flash", name: "Step 3.7 Flash", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "tencent/hy3-paid", name: "Tencent Hy3", reasoning: true, input: ["text"], contextWindow: 262144, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "tencent/hy4-preview", name: "Tencent Hy4 Preview", reasoning: true, input: ["text"], contextWindow: 1048576, maxTokens: 64000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "sakana/fugu-ultra", name: "Fugu Ultra", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 16384, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "thinkingmachines/inkling", name: "Inkling", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "thinkingmachines/inkling-small", name: "Inkling Small", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "poolside/laguna-s-2.1-free", name: "Laguna S 2.1", reasoning: true, input: ["text"], contextWindow: 256000, maxTokens: 32000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "inclusionai/ling-3.0-flash-sante:free", name: "Ling 3.0 Flash Sante", reasoning: true, input: ["text"], contextWindow: 262144, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meta/muse-spark-1.1", name: "Muse Spark 1.1", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meta/muse-spark-1.2", name: "Muse Spark 1.2", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meta/muse-spark-1.3", name: "Muse Spark 1.3", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "meta/muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "xai/grok-4.5", name: "Grok 4.5", reasoning: true, input: ["text","image"], contextWindow: 500000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "xai/grok-4.6", name: "Grok 4.6", reasoning: true, input: ["text","image"], contextWindow: 500000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
	],
	"scnet": [
		{ id: "MiniMax-M2.5", name: "MiniMax-M2.5", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "DeepSeek-V4-Flash", name: "DeepSeek-V4-Flash", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "DeepSeek-V4-Pro", name: "DeepSeek-V4-Pro", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Kimi-K2.6", name: "Kimi-K2.6", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "GLM-5.1", name: "GLM-5.1", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "MiniMax-M2.7", name: "MiniMax-M2.7", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "MiniMax-M3", name: "MiniMax-M3", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"minimal":"minimal","low":"low","medium":"medium","high":"high","xhigh":"xhigh"} },
		{ id: "Kimi-K2.5", name: "Kimi-K2.5", reasoning: true, input: ["text","image"], contextWindow: 256000, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "GLM-5", name: "GLM-5", reasoning: true, input: ["text"], contextWindow: 200000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0} },
		{ id: "GLM-5.2", name: "GLM-5.2", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Kimi-K2.7-Code", name: "Kimi-K2.7-Code", reasoning: true, input: ["text","image"], contextWindow: 262144, maxTokens: 65536, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"minimal":"minimal","low":"low","medium":"medium","high":"high","xhigh":"xhigh"} },
		{ id: "Kimi-K3", name: "Kimi-K3", reasoning: true, input: ["text","image"], contextWindow: 1048576, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "DeepSeek-V4-Flash-0731", name: "DeepSeek-V4-Flash-0731", reasoning: true, input: ["text"], contextWindow: 1048576, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen3.8-Max", name: "Qwen3.8-Max", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"minimal":"minimal","low":"low","medium":"medium","high":"high"} },
		{ id: "DeepSeek-V4-Pro-0813", name: "DeepSeek-V4-Pro-0813", reasoning: true, input: ["text"], contextWindow: 1048576, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "GLM-5.3", name: "GLM-5.3", reasoning: true, input: ["text"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "Qwen3.8-Flash", name: "Qwen3.8-Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"minimal":"minimal","low":"low","medium":"medium","high":"high"} },
		{ id: "GLM-5.3-Flash", name: "GLM-5.3-Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 131072, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
		{ id: "DeepSeek-V4.1-Flash", name: "DeepSeek-V4.1-Flash", reasoning: true, input: ["text","image"], contextWindow: 1000000, maxTokens: 384000, cost: {"input":0,"output":0,"cacheRead":0,"cacheWrite":0}, thinkingLevelMap: {"low":"low","high":"high","max":"max"} },
	],
};
